In [8]:
import numpy as np
import csv

In [14]:
test = np.genfromtxt('ccp.csv', delimiter=',', dtype=np.uint, skip_header=1)
print(test)
    

[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992   99   89 5100    1]
 [1992   99   90 5180    1]
 [1992   99   93 5100    1]]


[1 2 3]
